name: CI/CD Pipeline For Blog Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for the workflow (make sure the Node.js version matches your project version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set your Node.js version (adjust if necessary)

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run linting (optional but highly recommended for maintaining code quality)
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run the build (production-ready build of the app)
      - name: Build project
        run: npm run build

     